<a href="https://colab.research.google.com/github/stazam/ML-hackathon---genomic_benchmarks/blob/main/Introduction_script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install genomic-benchmarks

     |████████████████████████████████| 2.3 MB 8.4 MB/s 
     |████████████████████████████████| 596 kB 62.8 MB/s 
     |████████████████████████████████| 271 kB 57.9 MB/s 
     |████████████████████████████████| 160 kB 65.7 MB/s 
  Created wheel for genomic-benchmarks: filename=genomic_benchmarks-0.0.3-py3-none-any.whl size=17311 sha256=dac2a693ba371b178b94be87906ec0245ac9867fefcb92169999e207bdc81bf5
  Stored in directory: /root/.cache/pip/wheels/34/4f/f6/401d087f70557375a949ecbd3cf43e9cf9dcfc971ea77c12db
Successfully built genomic-benchmarks
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from genomic_benchmarks.data_check import list_datasets
list_datasets()

/usr/local/lib/python3.7/dist-packages/genomic_benchmarks/utils/datasets.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


['demo_coding_vs_intergenomic_seqs',
 'demo_human_or_worm',
 'human_enhancers_ensembl',
 'human_nontata_promoters',
 'demo_mouse_enhancers',
 'human_enhancers_cohn']

In [4]:
from genomic_benchmarks.data_check import info
info("human_nontata_promoters", version=0)

Dataset `human_nontata_promoters` has 2 classes: negative, positive.

All lenghts of genomic intervals equals 251.

Totally 36131 sequences have been found, 27097 for training and 9034 for testing.


train  test
negative  12355  4119
positive  14742  4915

In [6]:
from genomic_benchmarks.loc2seq import download_dataset
download_dataset("human_nontata_promoters", version=0)

Unzipping...Done.


PosixPath('/root/.genomic_benchmarks/human_nontata_promoters')

In [7]:
from pathlib import Path
import tensorflow as tf

In [11]:
SEQ_TRAIN_PATH = Path.home() / '.genomic_benchmarks' / 'human_nontata_promoters' / 'train'
BATCH_SIZE = 64
CLASSES = ['negative', 'positive']

In [12]:
train_dset = tf.keras.preprocessing.text_dataset_from_directory(
...     directory=SEQ_TRAIN_PATH,
...     batch_size=BATCH_SIZE,
...     class_names=CLASSES)

Found 27097 files belonging to 2 classes.


In [20]:
list(train_dset)[0][1]

<tf.Tensor: shape=(64,), dtype=int32, numpy=
array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
      dtype=int32)>

In [21]:
list(train_dset)[0][0]

<tf.Tensor: shape=(64,), dtype=string, numpy=
array([b'TTTTTAAAATACTGGAGGCCTTTCCTGGAGGGTTTCTCCTCTCCAGATGGCCCCAGAGCACCCCAAGCTCAGGACATGTCCCTCCCCAGCCAAGCTGTCTCCCTTTACTTCCTTTGCCTCCTCTCTCCCAATTATTTTGGCCCAAACTGATCAGTCCCGCTGGCCTCTCCCAAGCAGGTCCTTCTGGCACTCCTCTGGTGGACCGCCCCCATCGGCCACACTTGCCCTGCTCTCCAGTGATTCTGTAGCTC',
       b'CACCTGCTCTGTGCCTTGGCTGAGGCCCCTGCAGCTCTACAAGGCAGGCATTCTGCTGGATAGGCCAAGCAGGGTCACTCTGACACCCAGGTTTCCACCCCAAGGCATGGCACAATGCTGGCCTCCTGTGGGTGGAATCAAAGGCTGAGTTCTAACAGGCTTGCGGCAGACACACACACAGAGACCACATGTACATGATGAACACACATATCCTTTTCATTACAGGTTATTAGTACAAGTTTTGGAATTGA',
       b'TGTTCTCGGGCTTCAACGCAGACTACGAGGCGTCATCCTCCCGCTGCAGCAGCGCGTCCCCGGCCGGGGATAGCCTCTCTTACTACCACTCACCCGCAGACTCCTTCTCCAGCATGGGCTCGCCTGTCAACGCGCAGGTAAGGCTGGCTTCCCGTCGCCGCGGGGCCGGGGGCTTGGGGTCGCGGAGGAGGAGACACCGGGCGGGACGCTCCAGTAGATGAGTAGGGGGCTCCCTTGTGCCTGGAGGGAGG',
       b'GTAAGTCCTAGAGCTGGGAAAGGGCCTGGAACTAATGCCTAGGGTCCTGATTCATGTCCTGCCCTGACCACAGGAAAGTTGCCCATTGTAAATGAAGATGATGAGCTTGTGGCCATCATTGCCCGGACAGACCTGAAGAAGAATCGGGACTACCCA

In [38]:
import numpy as np

sequence1 = list(train_dset)[0][0][0]

In [46]:
sequence1 = 'CGGATCCCAGTTAGCCCGCGGCTCCAATCTGGTCCCCCCCCAACCCCGAGCCTCGCGGCGAGAAAGGAAGCGGCTCCGGATGGAGAGTAAAGTGACAATCGGAGAAGGGCAGGCTGCCTTTCCTCCCGGGGGAGCCAAGGGGACCTGCAGAGGGCGGTTTCTCTCCGCTTTTCCTGTCCCACCCCGTCGGCCTGCCCCCCACCCCCTCCGGCCTCTGCGCCAACCCCGCGCGCCACCCGCGGCTTCCTCCG'

In [52]:
print(set(sequence1))

{'G', 'C', 'T', 'A'}


In [53]:
from google.colab import drive
#drive.mount('/content/drive',  force_remount=True)
drive.mount('/content/drive',  force_remount=True)

Mounted at /content/drive


In [ ]:
sys.path.append('/content/drive/MyDrive/CEITEC/Python_files')

from help_functions import *